use crate::models::{Agent, Defaults};
use crate::{Error, Result};
use std::path::Path;

pub struct AgentManager {
    system_dir: std::path::PathBuf,
    generated_dir: std::path::PathBuf,
}

impl AgentManager {
    pub fn new(system_dir: &Path) -> Self {
        Self {
            system_dir: system_dir.to_path_buf(),
            generated_dir: system_dir.join("generated"),
        }
    }

    pub async fn apply_config(&self, agents: &[Agent], defaults: &Defaults) -> Result<()> {
        self.ensure_directories().await?;
        self.write_containers_nix(agents, defaults).await?;
        self.nixos_rebuild_switch().await?;
        Ok(())
    }

    async fn ensure_directories(&self) -> Result<()> {
        tokio::fs::create_dir_all(&self.generated_dir).await?;
        Ok(())
    }

    async fn write_containers_nix(&self, agents: &[Agent], defaults: &Defaults) -> Result<()> {
        let content = self.generate_containers_nix(agents, defaults);
        tokio::fs::write(self.generated_dir.join("container.nix"), content).await?;
        Ok(())
    }

    async fn nixos_rebuild_switch(&self) -> Result<()> {
        use tokio::io::{AsyncBufReadExt, BufReader};
        
        let flake_path = self.system_dir.to_string_lossy();
        println!("Running: sudo nixos-rebuild switch --flake {}#", flake_path);

        let mut child = tokio::process::Command::new("sudo")
            .args([
                "nixos-rebuild",
                "switch",
                "--flake",
                &format!("{}#", flake_path),
            ])
            .stdout(std::process::Stdio::piped())
            .stderr(std::process::Stdio::piped())
            .spawn()
            .map_err(|e| Error::Io(e))?;

        let stdout = child.stdout.take().ok_or_else(|| Error::Io(std::io::Error::new(
            std::io::ErrorKind::Other,
            "Failed to capture stdout",
        )))?;
        let stderr = child.stderr.take().ok_or_else(|| Error::Io(std::io::Error::new(
            std::io::ErrorKind::Other,
            "Failed to capture stderr",
        )))?;

        let mut stdout_reader = BufReader::new(stdout).lines();
        let mut stderr_reader = BufReader::new(stderr).lines();

        let mut stdout_eof = false;
        let mut stderr_eof = false;

        while !stdout_eof || !stderr_eof {
            tokio::select! {
                line = stdout_reader.next_line(), if !stdout_eof => {
                    match line {
                        Ok(Some(line)) => println!("{}", line),
                        Ok(None) => stdout_eof = true,
                        Err(e) => {
                            eprintln!("Error reading stdout: {}", e);
                            stdout_eof = true;
                        }
                    }
                }
                line = stderr_reader.next_line(), if !stderr_eof => {
                    match line {
                        Ok(Some(line)) => eprintln!("{}", line),
                        Ok(None) => stderr_eof = true,
                        Err(e) => {
                            eprintln!("Error reading stderr: {}", e);
                            stderr_eof = true;
                        }
                    }
                }
            }
        }

        let status = child.wait().await.map_err(|e| Error::Io(e))?;

        if !status.success() {
            return Err(Error::Config("nixos-rebuild failed".to_string()));
        }

        Ok(())
    }

    fn generate_containers_nix(&self, agents: &[Agent], defaults: &Defaults) -> String {
        if agents.is_empty() {
            return r#"# Auto-generated by ZS Platform
# No containers configured

{ config, pkgs, lib, ... }:

{
  # No containers
}
"#
            .to_string();
        }

        let mut containers = String::new();

        for agent in agents {
            let container = format!(
                r#"  containers.{name} = {{
    autoStart = {auto_start};
    ephemeral = false;
    privateNetwork = true;
    hostAddress = "{host_ip}";
    localAddress = "{container_ip}";
    
    config = {{ config, pkgs, lib, ... }}: {{
      imports = [
        zs-platform.nixosModules.zsw
      ];
      
      services.zs-platform.zsw = {{
        enable = true;
        package = zs-platform.packages.${{pkgs.stdenv.hostPlatform.system}}.zsw;
        agentName = "{name}";
        managerUrl = "ws://{host_ip}:{ws_port}";
        internalToken = "{token}";
        workspace = "/workspace";
      }};
      
      networking.firewall.allowedTCPPorts = [ 8080 ];
      
      system.stateVersion = "25.11";
    }};
  }};
"#,
                name = agent.name,
                auto_start = if agent.enabled { "true" } else { "false" },
                host_ip = agent.host_ip,
                container_ip = agent.container_ip,
                ws_port = defaults.port,
                token = agent.internal_token,
            );
            containers.push_str(&container);
        }

        format!(
            r#"# Auto-generated by ZS Platform
# DO NOT EDIT MANUALLY

{{ config, pkgs, lib, zs-components, ... }}:

{{
{containers}}}
"#
        )
    }
}